import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

const navigationConfig = [
    {
        key: 'home',
        path: '/home',
        title: 'Dashboard',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'parkings',
        path: '/parkings',
        title: 'Parkings',
        translateKey: 'nav.parkings',
        icon: 'parkings',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'parkingMap',
        path: '/parking-map',
        title: 'Parking Map',
        translateKey: 'nav.parkingMap',
        icon: 'parkingMap',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'myReservations',
        path: '/my-reservations',
        title: 'My Reservations',
        translateKey: 'nav.myReservations',
        icon: 'reservations',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'myPayments',
        path: '/my-payments',
        title: 'My Payments',
        translateKey: 'nav.myPayments',
        icon: 'payments',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'admin',
        path: '',
        title: 'Administration',
        translateKey: 'nav.admin',
        icon: 'admin',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['admin'],
        subMenu: [
            {
                key: 'admin.dashboard',
                path: '/admin/dashboard',
                title: 'Admin Dashboard',
                translateKey: 'nav.admin.dashboard',
                icon: 'adminDashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'admin.users',
                path: '/admin/users',
                title: 'Users',
                translateKey: 'nav.admin.users',
                icon: 'users',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'admin.reservations',
                path: '/admin/reservations',
                title: 'All Reservations',
                translateKey: 'nav.admin.reservations',
                icon: 'adminReservations',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'admin.payments',
                path: '/admin/payments',
                title: 'All Payments',
                translateKey: 'nav.admin.payments',
                icon: 'adminPayments',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
